{
 "title": "Kubernetes Container Resources",
 "description": "Kubernetes Container resources",
 "tags": [
  "prometheus",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "description": "# used formulas\n* [container_cpu_usage_seconds_total](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) to calculate the median CPU usage in % based on the cumulative CPU time consumed. If multiple threads are used their times are added to the sum",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container=~\"$container\", pod=~\"$pod\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPU throttling",
   "type": "gauge",
   "description": "# used formulas\n* ratio between [container_cpu_cfs_throttled_periods_total](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) and [container_cpu_cfs_periods_total](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) to calculate the median CPU throttling in %",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.50, rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[5m]) / rate(container_cpu_cfs_periods_total{namespace=~\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "gauge",
   "description": "# used formulas\n* [kube_pod_container_resource_limits](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md) is used to calculate the total configured CPU limits of the selected pods or containers",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",resource=\"cpu\",container=~\"$container\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "# Containers",
   "type": "gauge",
   "description": "# used formulas\n* [kube_pod_container_status_ready](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md) is used to calculate the number of ready containers of the selected pods or containers",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(min_over_time(kube_pod_container_status_ready{namespace=~\"$namespace\",container=~\"$container\", pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "RAM requests usage",
   "type": "gauge",
   "description": "# used formulas\n* median ratio between [container_memory_working_set_bytes](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) and [kube_pod_container_resource_requests](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md) in % (provided by the [container_memory_utilization_ratio](https://github.com/sapcc/helm-charts/blob/f1c6d7fe8c9093b16e73d292e2454816a192ec22/prometheus-rules/metrics-regional-rules/templates/aggregations/collector/_resource.rules.tpl#L32) formula)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.50, (\n    sum(container_memory_working_set_bytes) by (namespace, pod, container)\n    /\n    sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace, pod, container)\n    )\n)"
    }
   ]
  },
  {
   "title": "RAM limits usage",
   "type": "gauge",
   "description": "# used formulas\n* median ratio between [container_memory_working_set_bytes](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) and [kube_pod_container_resource_limits](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md) in % (provided by the [container_memory_saturation_ratio](https://github.com/sapcc/helm-charts/blob/f1c6d7fe8c9093b16e73d292e2454816a192ec22/prometheus-rules/metrics-regional-rules/templates/aggregations/collector/_resource.rules.tpl#L26) formula)\n* 100%  saturation means OOMKill!",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.50, (\n    sum(container_memory_working_set_bytes) by (namespace, pod, container)\n    /\n    sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (namespace, pod, container)\n    )\n)"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "description": "# used formulas\n* [container_memory_working_set_bytes](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) is used to calculate the total RAM usage of the selected pods or containers",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",container=~\"$container\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "RAM requests",
   "type": "gauge",
   "description": "# used formulas\n* [kube_pod_container_resource_requests](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md) is used to calculate the total RAM requests of the selected pods or containers",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",resource=\"memory\",container=~\"$container\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "RAM limits",
   "type": "gauge",
   "description": "# used formulas\n* [kube_pod_container_resource_limits](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md) is used to calculate the total configured RAM limits of the selected pods or containers",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",resource=\"memory\",container=~\"$container\", pod=~\"$pod\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU usage and throttling ratio",
   "type": "graph",
   "description": "# used formulas\n* [container_cpu_usage_seconds_total](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) to calculate the CPU usage in % based on the cumulative CPU time consumed. If multiple threads are used their times are added to the sum\n* [container_cpu_cfs_throttled_periods_total](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) to calculate the CPU throttling in % because of defined limits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, container) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container=~\"$container\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "cpu usage | {{pod}}/{{container}}"
    },
    {
     "expr": "sum by (pod, container) (rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[5m]) / rate(container_cpu_cfs_periods_total[5m]))",
     "legendFormat": "cpu throttling | {{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU usage and throttling periods",
   "type": "graph",
   "description": "# used formulas\n* [container_cpu_cfs_periods_total](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) is used to count the amount of CPU request periods that have triggered limit checks\n* [container_cpu_cfs_throttled_periods_total](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) is used to count the amount of throttled CPU request periods because of limit checks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "string", "label": "periods" }
   ],
   "targets": [
    {
     "expr": "round(rate(container_cpu_cfs_periods_total{container=~\"$container\",pod=~\"$pod\"}[5m]), 0.01)",
     "legendFormat": "periods | {{pod}}/ {{container}}"
    },
    {
     "expr": "round(rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\",container=~\"$container\", pod=~\"$pod\"}[5m]), 0.01)",
     "legendFormat": "throttled periods | {{pod}}/{{container}}"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "description": "# used formulas\n* [container_memory_working_set_bytes](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) to calculate the RAM usage of the container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",container=~\"$container\",pod=~\"$pod\"}) by (namespace, pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory usage to requests/limits ratio",
   "type": "graph",
   "description": "# used formulas\n* [container_memory_saturation_ratio](https://github.com/sapcc/helm-charts/blob/f1c6d7fe8c9093b16e73d292e2454816a192ec22/prometheus-rules/metrics-regional-rules/templates/aggregations/collector/_resource.rules.tpl#L26) is used to calculate the used memory to configured limits ratio\n* [container_memory_utilization_ratio](https://github.com/sapcc/helm-charts/blob/f1c6d7fe8c9093b16e73d292e2454816a192ec22/prometheus-rules/metrics-regional-rules/templates/aggregations/collector/_resource.rules.tpl#L32) is used to calculate the used memory to configured requests ratio",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes) by (namespace, pod, container)\n/\nsum(kube_pod_container_resource_limits{resource=\"memory\"}) by (namespace, pod, container)",
     "legendFormat": "used limits | {{pod}}/{{container}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes) by (namespace, pod, container)\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace, pod, container)",
     "legendFormat": "used request | {{pod}}/{{container}}"
    }
   ]
  }
 ]
}