{
 "title": "Kubernetes Node",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_node_status_capacity_cpu_cores{node=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$server\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$server\"}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (node) (irate(node_cpu_seconds_total{node=~\"$server\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{node=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Scrape CPU use",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_scrape_collector_duration_seconds{node=~\"$server\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(mode)(irate(node_cpu_seconds_total{node=~\"$server\", mode!=\"idle\"}[5m])) > 0",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$server\"} - node_memory_MemFree_bytes{node=~\"$server\"} - node_memory_Cached_bytes{node=~\"$server\"} - node_memory_Buffers_bytes{node=~\"$server\"} - node_memory_Slab_bytes{node=~\"$server\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=~\"$server\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{node=~\"$server\"} + node_memory_Slab_bytes{node=~\"$server\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"$server\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{node=~\"$server\", device!~\"lo|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{node=~\"$server\", device!~\"lo|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} inbound"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{node=~\"$server\"} / node_memory_MemTotal_bytes{node=~\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Pods CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{pod=~\".+\"}[5m])) by (pod, namespace) AND on (pod, namespace) (kube_pod_info{node=\"$server\"}))",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, container_memory_usage_bytes{pod=~\".+\"} AND on(pod) (kube_pod_info{node=\"$server\"}))",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Free Filesystem Space (Lowest)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{fstype=~\"xfs|ext4\",node=~\"$server\"} / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",node=~\"$server\"})"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (irate(node_disk_reads_completed_total{node=~\"$server\"}[5m]))",
     "legendFormat": "reads per second"
    },
    {
     "expr": "sum by (node) (irate(node_disk_writes_completed_total{node=~\"$server\"}[5m]))",
     "legendFormat": "writes per second"
    },
    {
     "expr": "sum by (node) (irate(node_disk_io_time_seconds_total{node=~\"$server\"}[5m]))",
     "legendFormat": "io time"
    },
    {
     "expr": "sum by (node) (irate(node_disk_reads_completed_total{node=~\"$server\"}[5m])) + sum by (node) (irate(node_disk_writes_completed_total{node=~\"$server\"}[5m]))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "IO Speed by Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{node=~\"$server\"}[5m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "NFS requests by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(node_nfs_requests_total{node=~\"$server\"}[5m])) > 0",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFS RPCs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(node_nfs_rpcs_total{node=~\"$server\"}[5m]))",
     "legendFormat": "NFS RPCs"
    }
   ]
  },
  {
   "title": "NFS RPC retransmissions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfs_rpc_retransmissions_total{node=~\"$server\"}[5m])",
     "legendFormat": "NFS RPC retransmissions"
    }
   ]
  }
 ]
}