## Common labels to add to all resources
##
commonLabels: {}

## Create default rules for monitoring the cluster
##
prometheusRules:

  ## Label selectors for the Prometheus rules to be picked up by Prometheus.
  ruleSelectors:
    # - name: plugin
    #   value: kube-monitoring
    # - name: prometheus
    #   value: kubernetes

  ## Labels for PrometheusRules
  labels: {}

  ## Annotations for PrometheusRules
  annotations: {}

  ## Additional labels for PrometheusRule alerts
  ## This is useful for adding additional labels such as "support_group" or "service" for the routing of alerts to each rule
  additionalRuleLabels:
    support_group: support
    # service: my-service

  ## Additional annotations for PrometheusRule alerts
  additionalRuleAnnotations: {}
