# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: kubernetes-operations
version: 1.0.0
description: A set of Plutono dashboards and Prometheus alerting rules combined with playbooks to ensure effective operations of Kubernetes.
maintainers:
  - name: Richard Tief (I520251)
    email: richard.tief@sap.com
sources:
  - ghcr.io/cloudoperators/kubernetes-operations
keywords:
  - Helm Chart
  - Kubernetes operations
  - Plutono Dashboards
  - Prometheus Alerting
  - Alert Rules
  - Playbooks
