name: Check & Fix License Header
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  generate-token:
    name: Generate GitHub App Token
    runs-on: [ ubuntu-latest ]
    outputs:
      token: ${{ steps.github-app-token.outputs.token }}
    steps:
      - name: Generate GitHub App Token
        id: github-app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.CLOUDOPERATOR_APP_ID }}
          private-key: ${{ secrets.CLOUDOPERATOR_APP_PRIVATE_KEY }}
          permission-contents: write

  license:
    name: Apply Licence Header
    needs: generate-token
    permissions:
      contents: write
    uses: cloudoperators/common/.github/workflows/shared-license.yaml@main
    with:
      pas: ${{ needs.generate-token.outputs.token }}
